### ISSUE TITLE
어느 정도 사용할 수 있게 돌아가는 버전은 어려울까요?

### ISSUE THREAD

**Issue by deveondcom** [mAKEkr/rhymix-board-skin-template#1]
빠진 부분들이 많아서 ㅠ
혹시 어느 정도 돌아가는 스킨 파일로 올려주심 안될까요?

**Comment by mAKEkr** [comment]
문의주셔서 감사합니다만.. 제가 현재 주업이 다른쪽인 상황이다보니 코드를 개선해서 내놓기가 좀 많이 어려운 상황입니다. 하루에 약 16시간동안 일하고 취미삼아 작업을 할수도 없는 상황이라서요.

최대한 저도 어느정도 시간이 나는대로 해당 스킨 완성해서 배포하고 싶은 마음이 크지만 지금 일단은 구조만 파악해주시고, 이러한 구조를 다른 게시판 스킨을 개발하실때 이용해주셨으면 하는 마음이 최우선적입니다.

해당 스킨의 기본골격이였던 XELAB-B1 스킨을 오픈소스로 공개하고싶지만, 구매하신분들에게 환불을 해드리고 싶어도 구매하신분들 목록을 찾기 힘든 상황이기도 하고 여러모로 많이 안따라주어 사실상 새로 작업하여 배포해야됩니다.

완성되면 퍼블릭 채널(XE타운)등에 게시하는 형태로 올려드리겠습니다.
